# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1630b74a0780c776b9f8783d3e6368eb57844e7ff49533ec7962089bb611f82a81f101414ccc9ce71f3966d1149b7d175ee1338bda7f9eb77f62903888d79503

test:
  secret_key_base: 23762cc7d6359805ff957fd6917355432aeff8e6b817a6c41d1a35a73d1d89cbcd396ab0738a0b0e633fd9b500100421d900a9315dd6e0eabcfd14d41942b3d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
